{
 "title": "Home Sensoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  location AS metric,\n  value\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'Temperature'\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Light Intensity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  location AS metric,\n  value\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'Light'\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) AS \"time\",\n  location AS metric,\n  value\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'Temperature'\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reading_time AS \"time\",\n  location AS metric,\n  value\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'Pressure'\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Light Intensity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) AS \"time\",\n  location AS metric,\n  value\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'Light'\nORDER BY reading_time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(reading_time) AS \"time\",\n  location AS metric,\n  value\nFROM SensorData\nWHERE\n  $__timeFilter(reading_time) AND\n  sensor = 'Pressure'\nORDER BY reading_time"
    }
   ]
  }
 ]
}